# Generated by Django 6.0.6 on 2026-06-06 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_location_transaction_partner_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_identifier', models.CharField(blank=True, max_length=255)),
                ('montant_service', models.DecimalField(decimal_places=2, default=25, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=25, max_digits=12)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('completed', 'Complétée'), ('cancelled', 'Annulée')], default='pending', max_length=12)),
                ('note', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_service_requests', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_service_requests', to=settings.AUTH_USER_MODEL)),
                ('partner_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='api.location')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'partner', 'statut'], name='api_partner_merchan_e3018e_idx'), models.Index(fields=['request_id'], name='api_partner_request_e0cc0e_idx')],
            },
        ),
    ]
