# Generated by Django 6.0.6 on 2026-06-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_partnerservicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance_en_attente',
        ),
        migrations.AddField(
            model_name='wallet',
            name='max_allowed_debt',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Dette maximale autorisée', max_digits=12),
        ),
        migrations.AddField(
            model_name='wallet',
            name='pending_debt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dette en attente (commissions de partenaires non payées)', max_digits=12),
        ),
    ]
