# Generated by Django 6.0.6 on 2026-06-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_wallet_balance_en_attente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='settled',
            field=models.BooleanField(default=False, help_text='Indique si la transaction a été réglée (portefeuilles mis à jour)'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='max_allowed_debt',
            field=models.DecimalField(decimal_places=2, default=500, help_text='Dette maximale autorisée', max_digits=12),
        ),
    ]
