from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import (
    APIRootView,
    APIDocsView,
    RegisterView,
    LoginView,
    MeView,
    UserProfileView,
    PartnerListView,
    PartnerLocationsView,
    PartnerServiceRequestView,
    PartnerServiceRequestAcceptView,
    PartnerServiceRequestCompleteView,
    WalletView,
    WalletWithdrawView,
    WalletRechargeView,
    WalletRechargeVerifyView,
    PaymentInitiateView,
    TransactionListCreateView,
    TransactionValidateView,
    QRScanView,
    DashboardView,
    AdminUsersView,
    AdminTransactionsView,
    AdminFraudView,
    AdminCommissionView,
    SeedTestUsersView,
    DebugAddBalanceView,
    LocationListView,
    LocationDetailView,
    LocationStatsView,
    NearbyLocationsView,
    CustomerListAPIView,
)

urlpatterns = [
    path('', APIRootView.as_view(), name='api-root'),
    path('docs/', APIDocsView.as_view(), name='api-docs'),
    path('auth/register/', RegisterView.as_view(), name='auth-register'),
    path('auth/login/', LoginView.as_view(), name='auth-login'),
    path('auth/me/', MeView.as_view(), name='auth-me'),
    path('auth/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('users/me/', UserProfileView.as_view(), name='user-profile'),
    path('customers/', CustomerListAPIView.as_view(), name='customer-list'),
    path('partners/', PartnerListView.as_view(), name='partner-list'),
    path('partners/<int:partner_id>/locations/', PartnerLocationsView.as_view(), name='partner-locations'),
    path('partner-requests/', PartnerServiceRequestView.as_view(), name='partner-service-requests'),
    path('partner-requests/<uuid:request_id>/accept/', PartnerServiceRequestAcceptView.as_view(), name='partner-service-request-accept'),
    path('partner-requests/<uuid:request_id>/complete/', PartnerServiceRequestCompleteView.as_view(), name='partner-service-request-complete'),
    path('locations/', LocationListView.as_view(), name='location-list'),
    path('locations/<int:pk>/', LocationDetailView.as_view(), name='location-detail'),
    path('locations/<int:pk>/stats/', LocationStatsView.as_view(), name='location-stats'),
    path('locations/nearby/', NearbyLocationsView.as_view(), name='location-nearby'),
    path('wallet/', WalletView.as_view(), name='wallet'),
    path('wallet/withdraw/', WalletWithdrawView.as_view(), name='wallet-withdraw'),
    path('wallet/recharge/', WalletRechargeView.as_view(), name='wallet-recharge'),
    path('wallet/recharge/verify/', WalletRechargeVerifyView.as_view(), name='wallet-recharge-verify'),
    path('payments/initiate/', PaymentInitiateView.as_view(), name='payment-initiate'),
    path('transactions/', TransactionListCreateView.as_view(), name='transactions'),
    path('transactions/<str:transaction_id>/validate/', TransactionValidateView.as_view(), name='transaction-validate'),
    path('qr/scan/', QRScanView.as_view(), name='qr-scan'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('admin/users/', AdminUsersView.as_view(), name='admin-users'),
    path('admin/transactions/', AdminTransactionsView.as_view(), name='admin-transactions'),
    path('admin/fraud/', AdminFraudView.as_view(), name='admin-fraud'),
    path('admin/commissions/', AdminCommissionView.as_view(), name='admin-commission'),
    path('debug/seed/', SeedTestUsersView.as_view(), name='debug-seed'),
    path('debug/add-balance/', DebugAddBalanceView.as_view(), name='debug-add-balance'),
]
